language: java

jdk:
  - openjdk12

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="b24d41f6-0ff2-41fd-b1d6-e51ba2b3ac43"

notifications:
  email:
    recipients:
      - frolovolegvladimirovich@gmail.com
    on_success: never # default: change
    on_failure: always # default: always